/** Declaration file generated by dts-gen */

export = markdown_it_imsize;

declare function markdown_it_imsize(md: any, options: any): void;

declare namespace markdown_it_imsize {
    const prototype: {
    };

}

